packages:
  - app-vite
  - app-vite/playground-js
  - app-vite/playground-ts
  - vite-plugin
  - vite-plugin/playground
  - extras
  - ui
  - ui/playground
  - ui/testing
  - create-quasar
  - cli
  - utils/render-ssr-error
  - utils/ssl-certificate

# The packages below are not included. Use their individual folders.
# - docs
# - icongenie
# - app-webpack
# - app-webpack/playground-js
# - app-webpack/playground-ts
# - utils/babel-preset-app
# - utils/ssr-helpers

catalog:
  vue: ^3.5.31
  vue-router: ^5.0.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - electron-winstaller
  - esbuild
  - lightningcss
  - unrs-resolver
